#!/usr/bin/env python3
"""Generate HOMEPLANET's lookup tables as a RASM include file.

This module is the *specification* for every table the engine reads. The tests
import it and re-derive the same numbers, then compare them against what is
actually sitting in the emulator's RAM -- so a table that silently changes
shape here fails the build's tests rather than corrupting the projection.

Usage:  python3 tools/gentables.py [--out src/gen/tables.asm]
"""

from __future__ import annotations

import argparse
import math
import os
import sys

# --- geometry, mirrored from src/equ/memmap.asm -----------------------------
SCR_HEIGHT_PX = 200
SCR_BYTES_PER_LINE = 80

# --- fixed point ------------------------------------------------------------
#  Trig is 8.8: 1.0 is stored as 256. Values therefore span -256..+256, which
#  needs 16 bits, which is why sin is split into two byte planes.
TRIG_ONE = 256
TRIG_STEPS = 256                     # a full turn in 256 brads
TRIG_QUARTER = TRIG_STEPS // 4       # cos(a) == sin(a + quarter)


def screen_line_offsets() -> list[int]:
    """Byte offset of each pixel line from the base of a screen buffer.

    The CPC interleaves: line L of character row R lives L*0x800 bytes into
    the buffer plus R*80. Stored as an offset rather than an address so the
    same table serves both buffers -- see scr_line_addr.
    """
    return [
        ((y & 7) * 0x800) + ((y >> 3) * SCR_BYTES_PER_LINE)
        for y in range(SCR_HEIGHT_PX)
    ]


def quarter_squares() -> list[int]:
    """f(n) = floor(n^2 / 4), for n in 0..511.

    The Z80 has no multiplier. The identity

        a * b = f(a + b) - f(a - b)

    turns an 8x8 multiply into two table reads and a subtraction, roughly 70
    T-states against ~200 for shift-and-add (Homeplanet.md section 4.2).

    One table covers both terms: a+b reaches 510, and |a-b| never exceeds 255,
    so the difference term indexes the same array. 512 entries, split into a
    low and a high byte plane, each page-aligned.
    """
    return [(n * n) // 4 for n in range(512)]


def sine_table() -> list[int]:
    """sin(angle) in 8.8 fixed point, 256 angles to the turn.

    Cosine is the same table read at (angle + 64) & 255, so nothing separate
    is stored for it.
    """
    return [
        round(TRIG_ONE * math.sin(2.0 * math.pi * i / TRIG_STEPS))
        for i in range(TRIG_STEPS)
    ]


# ---------------------------------------------------------------------------
#  Emission
# ---------------------------------------------------------------------------

def _split_planes(values: list[int]) -> tuple[list[int], list[int]]:
    """Split signed/unsigned 16-bit values into low and high byte planes."""
    lo, hi = [], []
    for v in values:
        w = v & 0xFFFF
        lo.append(w & 0xFF)
        hi.append(w >> 8)
    return lo, hi


def _defb_block(name: str, data: list[int], per_line: int = 16) -> str:
    out = [f"{name}:"]
    for i in range(0, len(data), per_line):
        chunk = ",".join("#%02X" % b for b in data[i:i + per_line])
        out.append(f"    defb {chunk}")
    return "\n".join(out)


def _defw_block(name: str, data: list[int], per_line: int = 8) -> str:
    out = [f"{name}:"]
    for i in range(0, len(data), per_line):
        chunk = ",".join("#%04X" % (w & 0xFFFF) for w in data[i:i + per_line])
        out.append(f"    defw {chunk}")
    return "\n".join(out)


def render() -> str:
    lines = [
        "; " + "=" * 74,
        ";  gen/tables.asm -- GENERATED by tools/gentables.py, do not edit",
        ";",
        ";  Regenerate with `make tables`. The generator is the readable",
        ";  specification; this file is just its output.",
        "; " + "=" * 74,
        "",
    ]

    # --- screen line offsets ------------------------------------------------
    offsets = screen_line_offsets()
    line_lo, line_hi = _split_planes(offsets)
    lines += [
        "; ---------------------------------------------------------------------------",
        ";  scr_line_lo / scr_line_hi -- byte offset of pixel line y from a buffer base.",
        ";",
        ";  Two byte planes on CONSECUTIVE pages, not one word table. That lets",
        ";  scr_line_addr index them with `ld h,page : ld l,y` and step between the",
        ";  planes with `inc h`, so it never needs a 16-bit register pair for the base",
        ";  -- which means it never clobbers DE, which callers hold their parameters in.",
        ";",
        ";  The offset never reaches #4000, so the buffer's high byte can be OR'd on",
        ";  rather than added.",
        "; ---------------------------------------------------------------------------",
        "    align 256",
        _defb_block("scr_line_lo", line_lo),
        "    align 256",
        _defb_block("scr_line_hi", line_hi),
        "",
        f"SCR_LINE_TABLE_ENTRIES equ {len(offsets)}",
        "",
    ]

    # --- quarter squares ----------------------------------------------------
    qsq = quarter_squares()
    qsq_lo, qsq_hi = _split_planes(qsq)
    lines += [
        "; ---------------------------------------------------------------------------",
        ";  qsq_lo / qsq_hi -- f(n) = n*n/4, n = 0..511, as two byte planes.",
        ";  a*b = f(a+b) - f(a-b). Both planes are page-aligned, so a 9-bit index is",
        ";      ld h,HIGH(qsq_lo) : ld l,a : jr nc,$+3 : inc h",
        "; ---------------------------------------------------------------------------",
        "    align 256",
        _defb_block("qsq_lo", qsq_lo),
        "    align 256",
        _defb_block("qsq_hi", qsq_hi),
        "",
    ]

    # --- sine ---------------------------------------------------------------
    sin = sine_table()
    sin_lo, sin_hi = _split_planes(sin)
    lines += [
        "; ---------------------------------------------------------------------------",
        ";  sin_lo / sin_hi -- sin(a) * 256, 256 angles to the turn, two's complement.",
        ";  cos(a) = sin((a + 64) & 255). Page-aligned: ld h,HIGH(sin_lo) : ld l,angle",
        "; ---------------------------------------------------------------------------",
        f"TRIG_ONE     equ {TRIG_ONE}",
        f"TRIG_STEPS   equ {TRIG_STEPS}",
        f"TRIG_QUARTER equ {TRIG_QUARTER}",
        "",
        "    align 256",
        _defb_block("sin_lo", sin_lo),
        "    align 256",
        _defb_block("sin_hi", sin_hi),
        "",
    ]

    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=os.path.join(here, "src", "gen", "tables.asm"))
    args = ap.parse_args(argv)

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    text = render()
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"wrote {args.out} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
