#!/usr/bin/env python3
"""Pack a table of zero-terminated strings into FIVE BITS A CHARACTER.

    python3 tools/packtext.py src/game/briefings.asm src/gen/briefings_packed.asm

The briefings are sixty lines of capitals, spaces, full stops and commas --
twenty-nine symbols -- in bank 7, and bank 7 was full to the byte. Five bits
is 32 codes, the decoder (game/textpack.asm, b7_packed) is fifty bytes and a
32-byte alphabet, and the saving is three eighths of the text: about six
hundred bytes of the bank, which is what the cockpit's scanner runs in.

THE FORMAT, which tests/test_textpack.py holds the Z80 decoder to:

    TEXT_PACKED                  one byte, #FF, in front of the table: no raw
                                 string begins with it, so bank7_fetch's body
                                 tells the two kinds of table apart by it
    then, per string:
      length                     the packed bytes that follow, so a line is
                                 stepped over by an add rather than decoded
      packed bits                MSB first, five a code, code 0 ending the
                                 string; the last byte padded with zero bits

The alphabet is ALPHABET below, indexed by code: 0 is the terminator, 1-26
the letters, then space, full stop, comma, hyphen and apostrophe. A string
with any other character in it, or one that would not fit the decoder's
buffer, stops the build here rather than drawing rubbish on the machine.

Source strings are read out of the .asm, one `defb "...",0` a line, in
order; the .asm is the authored text and is NOT assembled itself.
"""

import re
import sys

TEXT_PACKED = 0xFF
ALPHABET = "\0ABCDEFGHIJKLMNOPQRSTUVWXYZ .,-'"
assert len(ALPHABET) == 32
BITS = 5
MAX_CHARS = 39          # B7_BUF_SIZE - 1: the terminator wants the last byte

STRING_RE = re.compile(r'^\s*defb\s+"((?:[^"\\]|\\.)*)"\s*,\s*0\s*(?:;.*)?$')


def strings_in(path: str) -> list[str]:
    """Every `defb "...",0` in the file, in order."""
    out = []
    with open(path) as f:
        for line in f:
            m = STRING_RE.match(line)
            if m:
                out.append(m.group(1))
    return out


def pack_line(s: str) -> bytes:
    """One string as its length byte and its packed bits."""
    if len(s) > MAX_CHARS:
        raise ValueError(f"{s!r} is {len(s)} characters; the decoder's buffer holds {MAX_CHARS}")
    bits = 0
    n = 0
    for ch in s + "\0":
        code = ALPHABET.find(ch)
        if code < 0:
            raise ValueError(f"{ch!r} in {s!r} is not in the packed alphabet")
        bits = (bits << BITS) | code
        n += BITS
    pad = (-n) % 8
    bits <<= pad
    n += pad
    body = bits.to_bytes(n // 8, "big")
    if len(body) > 255:
        raise ValueError(f"{s!r} packs to {len(body)} bytes")
    return bytes([len(body)]) + body


def pack_table(strings: list[str]) -> bytes:
    return bytes([TEXT_PACKED]) + b"".join(pack_line(s) for s in strings)


def unpack_line(data: bytes, at: int) -> tuple[str, int]:
    """The string whose length byte is at `at`, and the offset just past it --
    decoded the way b7_packed does it, so a test can hold the two together."""
    length = data[at]
    at += 1
    end = at + length
    out = []
    acc, have = 0, 0
    pos = at
    while True:
        while have < BITS:
            if pos >= end:
                raise ValueError("the packed line ran out before its terminator")
            acc = (acc << 8) | data[pos]
            pos += 1
            have += 8
        code = (acc >> (have - BITS)) & ((1 << BITS) - 1)
        have -= BITS
        if code == 0:
            break
        out.append(ALPHABET[code])
    return "".join(out), end


def unpack_table(data: bytes, at: int, count: int) -> list[str]:
    """`count` strings out of a packed table whose marker byte is at `at`."""
    if data[at] != TEXT_PACKED:
        raise ValueError(f"no TEXT_PACKED marker at {at:#x}")
    at += 1
    out = []
    for _ in range(count):
        s, at = unpack_line(data, at)
        out.append(s)
    return out


def emit(strings: list[str], src: str, label: str) -> str:
    lines = [f"; Generated by tools/packtext.py from {src} -- do not edit.",
             f"; {len(strings)} strings, five bits a character; the format is in the tool.",
             f"{label}:",
             f"    defb TEXT_PACKED"]
    for s in strings:
        packed = pack_line(s)
        hexes = ", ".join(f"#{b:02X}" for b in packed)
        lines.append(f"    defb {hexes}    ; {s}")
    lines.append(f"{label}_end:")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__)
        return 2
    src, dst = argv[1], argv[2]
    strings = strings_in(src)
    if not strings:
        print(f"packtext: no strings found in {src}", file=sys.stderr)
        return 1
    m = re.search(r"^([a-z_0-9]+):\s*$", open(src).read(), re.M)
    label = m.group(1) if m else "packed_text"
    packed = pack_table(strings)
    assert unpack_table(packed, 0, len(strings)) == strings, "the packer does not round-trip"
    with open(dst, "w") as f:
        f.write(emit(strings, src, label))
    raw = sum(len(s) + 1 for s in strings)
    print(f"packtext: {len(strings)} strings, {raw} bytes raw -> {len(packed)} packed")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
